### ISSUE TITLE
Support for visually impaired in registration process

### ISSUE THREAD

**Issue by streety** [toldani/sm-transition#1]
Currently the visually impaired are encouraged to send a message to the admin as an alternative to solving the CAPTCHA. I sent a couple of messages using the form and did not receive them as either private messages on the forum or as email.

We need to ensure that messages are received by someone who can act on them.

**Comment by toldani** [comment]
I switched to Q&A captchas and added a few questions that are simple enough for a person but would be hard for a bot.  Better?
